CREATE DATABASE tienda;
USE DATABASE tienda;

DROP TABLE if EXISTS productos;
CREATE TABLE productos(
idProducto INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nombre VARCHAR(100),
descripcion VARCHAR(255),
precio DOUBLE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);






